### ISSUE TITLE
Mismatch between Inverter SOC and Battery SOC

### ISSUE THREAD

**Issue by Jim-Battle67** [GivEnergy/giv_tcp#26]
I am noticing a bit of a mismatch between what is reported as the Inverters SOC and the Battery's own metric. It has been usual for this to differ by a % or so, but today, I am seeing the Battery showing 78% charged and the inverter showing 100% charged.

Anyone know if this normal, an issue with the integration or something I should be worried about.

It is a little frustrating if it is really only 78% charged to see KW of electricity being dumped to the grid for nothing.

**Comment by G6EJD** [comment]
What does the App report when you tap on the Battery icon, then more information ? Mine says Primary 74%, Secondary 46% and total 56% there is no obvious relationship that I can see. The integration reports exactly the same values.

**Comment by Jim-Battle67** [comment]
I only have one battery.

Checked the App and looks like it is consistently out of synch - so no bug in the integration software :-)

Did a reboot of the inverter and the 2 values syched up (with 1%), so appears to be a feature/bug of the battery/inverter combination.
